kind = "web"
previewPath = "/"
title = "NyrethaStore"
version = "1.0.0"
id = "artifacts/nyreth-store"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24102

[services.development]
run = "pnpm --filter @workspace/nyreth-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nyreth-store", "run", "build" ]
serve = "static"
publicDir = "artifacts/nyreth-store/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24102"
BASE_PATH = "/"
